version: "3"

services:

  mongo:
    image: mongo
    command: mongod --port 27018
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data/mongo/volume:/data/db
    ports:
      - 27018:27018
    networks:
      - githunter-data-provider-net

  data-provider:
    build: .
    image: githunter-data-provider:1.0
    restart: always
    ports:
      - 3333:3333
    networks:
      - githunter-data-provider-net

networks:
  githunter-data-provider-net:
